name: cicd

on:
  push:
    paths:
        - src/**
    branches:
        - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - 
        name: Shorten Commit ID
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::06}" >> "$GITHUB_ENV"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: johnmonteir0/python-app:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - 
        name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}' charts/python-app/values.yaml
      
      -
        name: Commit changes
        uses: Endbug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - 
        name: Install argocd
        shell: bash
        run: |
          curl  -ksSL -o argocd https://argocd.654654498256.realhandsonlabs.net/download/argocd-linux-amd64
          sudo chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - 
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd.654654498256.realhandsonlabs.net \
           --insecure \
           --grpc-web \
           --username admin \
           --password ${{  secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app